### ISSUE TITLE
Feature Request: Support method annotations starting with @something \\n

### ISSUE THREAD

**Issue by Szandor72** [btamburrino/VSCode-Apex-Javadoc#3]
Context:

```java
@AuraEnabled 
public static Map<String,String> fetchDataById(String RecordId) {
//...
}
```

When typing /** before an @ annotated method, a correct javadoc comment should be produced.

**Comment by btamburrino** [comment]
New version 1.0.3 was just pushed to the marketplace that should handle these correctly. Thanks for using the extension!
